### ISSUE TITLE
If not running this from an AWS EC2 instance, it complains with the AWS Provider

### ISSUE THREAD

**Issue by kjw3** [equinix/terraform-equinix-metal-openshift-on-baremetal#14]
When executing on a non-ec2 linux machine, I had to comment out the AWS provider because it was looking for the machine to have AWS roles assigned.

**Comment by displague** [comment]
Between #21 and #31 this should now be resolved.

I ran into the same limitations and set `provider {}` configuration that disables the AWS checks when `aws` is not the selected DNS provider.
